# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  phpunit:
    docker:
      - image: circleci/php:7.3.8
    steps:
      - checkout
      - run:
          name: Composer Install
          command: composer install
      - run:
          name: Run PHPUint
          command: vendor/bin/phpunit --bootstrap tests/TestBootstrap.php tests
workflows:
  version: 2
  build:
    jobs:
      - phpunit
